### ISSUE TITLE
Jenkins style updates

### ISSUE THREAD

**Issue by mvboeke** [cmonty/brainiac#15]
* Success text should be in blue, to match Jenkins' suit
* Long build names look kinda janky. Text should be set to overflow, instead of wrap.
* Instead of displaying "0 builds failing" it should read "All builds pass". You've got to ac-ceeeeeeen-tuate the positive.

**Comment by mikepilat** [comment]
These suggestions were incorporated/subsumed by 93cf3fe9bf1c4926a329b5cbdea00e1843bee63f.
